version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8000-8100:8000-8100
    restart: unless-stopped
    volumes: 
      - ./var/www/:/var/www/
      - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_7.3
      - db
    networks: 
      - legacy
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: dev
  php_7.3:
    build: 
      context: ./
      dockerfile: ./php_7.3/Dockerfile
      args:
        - SOURCE_PATH=./
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./var/www/:/var/www/
    networks: 
      - legacy
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - legacy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 52:80
    volumes:
     - /sessions
    networks:
      - legacy
    depends_on:
      - db
networks: 
  legacy:
    driver: bridge

volumes:
  dbdata:
    driver: local